const express=require("express");
const path=require("path");
require("./config/db");
const app=express();
const PORT=3000;
app.use(express.json());
app.use(express.urlencoded({extended:true}));
app.use("/api",require("./routes/contactRoutes"));
app.use(express.static(path.join(__dirname,"public")));
app.get("/",(req,res)=>res.sendFile(path.join(__dirname,"public","index.html")));
app.listen(PORT,"0.0.0.0",()=>console.log(`Server running on port ${PORT}`));
